### ISSUE TITLE
Serving

### ISSUE THREAD

**Issue by tjvr** [nathan/parcel#2]
What do cool people such as yourself do when they want to `prcl -w` concurrently with running, say, a local HTTP server? :-)

**Comment by nathan** [comment]
<code>[http-server](https://www.npmjs.com/package/http-server) -s & prcl -w main.js bundle.js</code>

**Comment by tjvr** [comment]
Cheers! I hadn't realised you could use `&` in NPM scripts -- this used to require a separate library like `concurrently`, AFAICT. Thanks also for the `-s` tip :-)

**Comment by nathan** [comment]
I probably would not put that all in one NPM script; I'd have a separate one for serving and watching and then do `npm start serve& npm start watch` (or use `make`).

**Comment by tjvr** [comment]
Okay, thanks :)
