### ISSUE TITLE
Require as string

### ISSUE THREAD

**Issue by heyitsmeuralex** [nathan/parcel#5]
I'd like to include a text file in my parcel, e.g.
```
hello world
```

At the moment, `require()`ing it results in - as expected - the JS code "hello world," which is a syntax error. I'd like to somehow `require.raw` files to be imported as if they were simply a string, so
```js
const helloWorld = require.raw('./hello.txt')
console.log(helloWorld) // hello world
```

Is this something we could make parcel do?

**Comment by nathan** [comment]
No.

**Comment by nathan** [comment]
Issue in new repository: https://github.com/nathan/parcel-redux/issues/1
