### ISSUE TITLE
require doesn't assume `index.js`

### ISSUE THREAD

**Issue by lightblub** [nathan/parcel#6]
In Node, `require('./somedirectory')` will attempt to load `somedirectory/index.js` and then `somedirectory/index.json`. Should parcel be doing something similar?

```js
require('./somedirectory')
// attempt "somedirectory"
// attempt "somedirectory.js"
// attempt "somedirectory.json"
// attempt "somedirectory/index.js"
// attempt "somedirectory/index.json"
// throw error
```

**Comment by nathan** [comment]
Yes, it already does.

**Comment by lightblub** [comment]
🤔 At some point I thought it didn't - must've been some kind of mistake on my part. Whoops, sorry!

**Comment by lightblub** [comment]
Oh, I see why. **parcel requires a trailing slash**, which isn't Node behaviour iirc...

**Comment by nathan** [comment]
> parcel requires a trailing slash

That's not correct. Here is a working example:

```js
// index.js
console.log(require('./sub'))

// sub/index.js
module.exports = 'foobar'
```

```sh
$ node -e "$(prcl index.js)"
foobar
```

Could you provide an example of something that doesn't match node's behavior?

**Comment by lightblub** [comment]
> Are you on Windows, by any chance? I don't use it very frequently, so the path behavior might not be correct.

Nope, not on Windows. Fedora user here.

Ugh, suddenly I can't reproduce it - sorry 😜 If I encounter it again I'll mention it.

**Comment by nathan** [comment]
No problem. Let me know if you have other issues :)
